Create change
Uploaded patch set 1.

Patch-set: 1
Change-id: I6ab002352b3272898ad0b183341ee664652c8ae3
Subject: Fixed NoClassDefFoundError when USE_SCRIPT_COMPILE_CACHE is set to false
Branch: refs/heads/master
Status: new
Topic: cluster-message
Commit: d41bab6ff4563d62f06ab226d30ad580ec71091c
Tag: autogenerated:gerrit:newPatchSet
Groups: d41bab6ff4563d62f06ab226d30ad580ec71091c
Reviewer: Gerrit User 6218 <6218@14b4e41f-c4e3-4fb9-9955-6a9b5656895a>
Private: false
Work-in-progress: false