Create patch set 3
Patch Set 3: Patch Set 2 was rebased

Patch-set: 3
Patch-set-description: Rebase
Subject: Fixed NoClassDefFoundError when USE_SCRIPT_COMPILE_CACHE is set to false
Commit: 55e4780ba5f1de52060eaf76608a588b5be7c788
Tag: autogenerated:gerrit:newPatchSet
Groups: 27a68320b862302f8d7dce7605ecdac2d8dc767f