Create patch set 2
Uploaded patch set 2.

Patch-set: 2
Subject: Fixed NoClassDefFoundError when USE_SCRIPT_COMPILE_CACHE is set to false
Commit: 27a68320b862302f8d7dce7605ecdac2d8dc767f
Tag: autogenerated:gerrit:newPatchSet
Groups: 27a68320b862302f8d7dce7605ecdac2d8dc767f